export const USER_LOGIN_START = "USER_LOGIN_START";
export const USER_CLEAR_AUTH_STATE = "USER_CLEAR_AUTH_STATE";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILED = "USER_SIGNUP_FAILED"
export const USER_SIGNUP_START = "USER_SIGNUP_START";

// 
export const ADMIN_LOGIN_START = "ADMIN_LOGIN_START";
export const ADMIN_CLEAR_AUTH_STATE = "ADMIN_CLEAR_AUTH_STATE";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAILED = "ADMIN_LOGIN_FAILED";
export const ADMIN_SIGNUP_SUCCESS = "ADMIN_SIGNUP_SUCCESS";
export const ADMIN_SIGNUP_FAILED = "ADMIN_SIGNUP_FAILED"
export const ADMIN_SIGNUP_START = "ADMIN_SIGNUP_START";